# 베이스 이미지 설정
FROM openjdk:17-jdk-slim

# 작업 디렉토리 설정
WORKDIR /app

# 빌드된 JAR 파일을 이미지에 추가
COPY build/libs/*.jar app.jar

# 환경 변수를 통해 프로파일 설정
ARG PROFILE=prod
ENV SPRING_PROFILES_ACTIVE=${PROFILE}

# 애플리케이션 포트 설정
EXPOSE 8080

# 애플리케이션 실행 명령어
ENTRYPOINT ["java", "-jar", "app.jar"]
